name: Format

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.90"
          components: rustfmt
      - run: cargo fmt --all -- --check
